### ISSUE TITLE
TypeError while reading image

### ISSUE THREAD

**Issue by andreash** [mattiasw/ExifReader#62]
### Description

I get a TypeError "e.map is not a function" in exifreader.

**How to reproduce**

1. Use attached image to read tags.

**What I expected would happen:**

That it reads the image.

**What really happened:**
exifreader throws an error.
Error reading file /media/data/pictures/sorted/2010er/2016/2016-06-29 Passbilder Linus/IMG_8225.CR2.jpg:  TypeError: e.map is not a function
    at Object.description (/home/andreas/SW-Projekte/phototags/node_modules/exifreader/dist/exif-reader.js:1:26789)
    at g (/home/andreas/SW-Projekte/phototags/node_modules/exifreader/dist/exif-reader.js:1:36099)
    at p (/home/andreas/SW-Projekte/phototags/node_modules/exifreader/dist/exif-reader.js:1:34904)
    at /home/andreas/SW-Projekte/phototags/node_modules/exifreader/dist/exif-reader.js:1:36776
    at Object.read (/home/andreas/SW-Projekte/phototags/node_modules/exifreader/dist/exif-reader.js:1:36808)
    at y (/home/andreas/SW-Projekte/phototags/node_modules/exifreader/dist/exif-reader.js:1:40864)
    at Object.m [as load] (/home/andreas/SW-Projekte/phototags/node_modules/exifreader/dist/exif-reader.js:1:40361)
    at processFile (/home/andreas/SW-Projekte/phototags/main.js:134:23)
    at /home/andreas/SW-Projekte/phototags/main.js:263:24
    at Array.forEach (<anonymous>)

![IMG_8225 CR2](https://user-images.githubusercontent.com/95178/67974073-febdb580-fc11-11e9-98da-66273e4f1050.jpg)

**Comment by mattiasw** [comment]
Confirmed. I will have a look at it. Thanks for the report!

**Comment by mattiasw** [comment]
The problem was a faulty tag value in the image. I guess you can't count on them always being according to the spec (unless I missed something...). This branch should fix your problem if you want to try it out. I'll make a new release during the weekend.

#63

**Comment by mattiasw** [comment]
Merged and new release created (2.8.5). Thanks for helping out!
